type Survey {
  id: Int!
  category: String!
  writter: String!
  createdAt: DateTime
  updatedAt: DateTime
  admissionQuestion: [AdmissionQuestion]
}

type AdmissionQuestion {
  id: Int!
  question: String!
  answer: String!
  survey: Survey
  surveyId: Int!
  createdAt: DateTime
  updatedAt: DateTime
}

type Mutation {
  createSurvey(category: String!, writter: String!): CommonResponse!
  editSurvey(id: Int!, category: String!, writter: String!): CommonResponse!
  createAQ(surveyId: Int!, question: String!, answer: String!): CommonResponse!
  editAQ(id: Int!, question: String, answer: String!): CommonResponse!
}
