type Exam {
  id: Int!
  title: String!
  tester: TUser!
  tUserId: Int!
  subjectName: String
  Question: [ExamQuestion]
  createdAt: String!
  updatedAt: String!
}
type ExamQuestion {
  id: Int!
  Exam: Exam
  examId: Int!
  item: String! #문제
  indexNum: Int! # 문제번호
  answer: String! #답
  #제출한답
  ExamAnswer: [ExamAnswer]
}

type ExamAnswer {
  id: Int
  stName: String
  ExamQuestion: ExamQuestion
  examQuestionId: Int
  tUser: TUser
  tUserId: Int
}
type Mutation {
  createExam(title: String!, subjectName: String!): CommentResponse!
  editExam(id: Int!, title: String, subjectName: String): CommentResponse!
  deleteExam(id: Int!): CommentResponse!
}
