type TUser {
  id: Int
  tpassword:String
  name: String
  email: String
}
type FindAllResponse {
  ok: Boolean!
  data: [TUser]
}

type Mutation {
    createUser(
    name:String
    password:String
    email:String
    ):CommentResponse
}
type Query {
  allUsers: FindAllResponse
}