type TUser {
  id: Int!
  name: String!
  password: String!
  email: String!
  phoneNum: String!
  rating: String #등급
  Exam: [Exam]
  ExamAnswer: [ExamAnswer]
}
type FindAllResponse {
  ok: Boolean!
  data: [TUser]
}
type LoginResult {
  ok: Boolean
  error: String
  token: String
}
type Mutation {
  createUser(
    name: String!
    password: String!
    email: String!
    phoneNum: String!
  ): CommentResponse
  editUser(
    id: Int!
    name: String
    password: String
    email: String
    phoneNum: String
    rating: String
  ): CommentResponse
  login(name: String, password: String): LoginResult
}
type Query {
  allUsers: FindAllResponse
}
