type TUser {
  id: Int
  tpassword: String
  name: String
  email: String
}
type FindAllResponse {
  ok: Boolean!
  data: [TUser]
}
type LoginResult {
  ok: Boolean
  error: String
  token: String
}
type Mutation {
  createUser(
    name: String
    password: String
    email: String
    phoneNum: String
  ): CommentResponse
  login(name: String, password: String): LoginResult
}
type Query {
  allUsers: FindAllResponse
}
