type TUser {
  id: Int
  tpassword:String
  name: String
  email: String
}
type FindAllResponse {
  ok: Boolean!
  data: [TUser]
}
type loginResult {
  ok:Boolean
  error:String
  token:String
}
type Mutation {
    createUser(
    name:String
    password:String
    email:String
    ):CommentResponse
    login(name:String password:String):loginResult
}
type Query {
  allUsers: FindAllResponse
}