type ExamQuestion {
  id: Int
  Exam: Exam
  examId: Int
  item: String #문제
  indexNum: Int #문제번호
  answer: String #답
  filePath: [String] # 파일을 올리고 (controller 를 이용하여) url을 저장하면 됩니다
  #제출한답
  ExamAnswer: [ExamAnswer]
  createdAt: String
  updatedAt: String
  lastModifiedTime: String
  lastModifiedByName: String
}

type Mutation {
  createExamQuestion(
    examId: Int!
    item: String!
    indexNum: Int!
    answer: String! #답
    fileUrl: [String]!
  ): CommonResponse!
}
