type TUser {
  id: Int
  name: String
  email: String
}
type FindAllResponse {
  ok: Boolean!
  data: [TUser]
}

type Query {
  allUsers: FindAllResponse
}

type CreateCommentResponse {
  ok: Boolean!
  error: String
  message: String
}

type Mutation {
  createComment(name: String, content: String): CreateCommentResponse
}
type Comment {
  id: Int!
  name: String!
  content: String!
  createdAt: String
  updatedAt: String
}
